services:
  - type: web
    name: attendance-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT run:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0